server:
  port: 8080

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://35.168.202.46:8081}

spring:
  application:
    name: bidmart-api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      server:
        webmvc:
          routes:
            # 1. Rute ke Modul Authentication
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://35.168.202.46:8081}
              predicates:
                - Path=/api/auth/**, /api/profile/**, /api/admin/**

            # 2. Rute ke Modul Lelang (Auction)
            - id: auction-service
              uri: ${AUCTION_SERVICE_URL:http://52.45.239.233:8082}
              predicates:
                - Path=/api/auctions/**

            # 3. Rute ke Modul Katalog
            - id: katalog-service
              uri: ${CATALOG_SERVICE_URL:http://34.194.85.48:8083}
              predicates:
                - Path=/listings/**, /api/categories/**, /api/listings/internal/**

            # 4. Rute ke Modul Dompet (Wallet)
            - id: wallet-service
              uri: ${WALLET_SERVICE_URL:http://34.226.162.160:8084}
              predicates:
                - Path=/api/wallet/**

            # 5. Rute ke Modul Notifikasi
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/order-notification/**, /api/notifications/**
